version: "3.1"

services:
  db:
    image: kryha/pgvectorcron
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  test-db:
    image: kryha/pgvectorcron
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test-example
    ports:
      - 5445:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
