apiVersion: skaffold/v3
kind: Config
metadata:
  name: bot-busters
build:
  tagPolicy:
    sha256: {}
  local:
    concurrency: 0
  artifacts:
    - image: bot-busters
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NEXT_PUBLIC_ALEO_NETWORK: testnet3
          NEXT_PUBLIC_WS_URL: ws://bot-busters.localhost
manifests:
  kustomize:
    paths:
      - ./deployment/local/
deploy:
  kubectl: {}
