apiVersion: skaffold/v3
kind: Config
metadata:
  name: bot-busters
build:
  tagPolicy:
    sha256: {}
  local:
    concurrency: 0
  artifacts:
    - image: eu.gcr.io/aleo-botbusters/bot-busters/bot-busters-staging
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NEXT_PUBLIC_ALEO_NETWORK: testnet3
          NEXT_PUBLIC_WS_URL: wss://bot-busters.staging.kryha.dev
    # TODO: delete
    - image: eu.gcr.io/aleo-botbusters/bot-busters/postgres
      docker:
        dockerfile: Dockerfile.postgres
manifests:
  kustomize:
    paths:
      - ./deployment/staging/
deploy:
  kubectl: {}
