apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bot-busters
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bot-busters
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metric:
          name: active_connections_total
        target:
          type: AverageValue
          averageValue: "4000"
