apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-busters
spec:
  selector:
    matchLabels:
      app: bot-busters
  template:
    metadata:
      labels:
        app: bot-busters
    spec:
      containers:
        - name: bot-busters
          resources:
            requests:
              cpu: 500m
              memory: 1024Mi
            limits:
              cpu: "1"
              memory: 2048Mi
          ports:
            - containerPort: 3000
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
