apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:8
          resources:
            requests:
              cpu: 470m
              memory: 512Mi
            limits:
              cpu: 940m
              memory: 1024Mi
          ports:
            - containerPort: 80
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PGADMIN_DEFAULT_EMAIL
              value: admin@admin.com
              # TODO: update default
            - name: PGADMIN_DEFAULT_PASSWORD
              value: root
              # valueFrom:
              #   secretKeyRef:
              #     name: backend-secrets
              #     key: db_password
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: db_password
            - name: DATABASE_URL
              value: postgresql://postgres:$(DB_PASSWORD)@postgres.$(POD_NAMESPACE).svc.cluster.local:5432
