apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: eu.gcr.io/aleo-botbusters/bot-busters/postgres:latest
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: db_password
            - name: PGDATA
              value: /data/pgdata
          volumeMounts:
            - name: postgres-data
              mountPath: /data
          ports:
            - containerPort: 5432
              name: http
              protocol: TCP

        - name: pgadmin
          image: dpage/pgadmin4:8
          # resources:
          #   requests:
          #     cpu: 470m
          #     memory: 512Mi
          #   limits:
          #     cpu: 940m
          #     memory: 1024Mi
          ports:
            - containerPort: 80
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PGADMIN_DEFAULT_EMAIL
              value: admin@admin.com
              # TODO: update default
            - name: PGADMIN_DEFAULT_PASSWORD
              value: root
              # valueFrom:
              #   secretKeyRef:
              #     name: backend-secrets
              #     key: db_password
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
