apiVersion: v1
kind: Service
metadata:
  name: bot-busters
  labels:
    app: bot-busters
spec:
  type: ClusterIP
  selector:
    app: bot-busters
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: bot-busters
