apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-busters
spec:
  selector:
    matchLabels:
      app: bot-busters
  template:
    spec:
      containers:
        - name: bot-busters
          image: bot-busters
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: db_password
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: nextauth_secret
            - name: DATABASE_URL
              value: postgresql://postgres:$(DB_PASSWORD)@postgres.$(POD_NAMESPACE).svc.cluster.local:5432
            - name: NEXTAUTH_URL
              value: http://bot-busters.localhost
            - name: NEXTAUTH_URL_INTERNAL
              value: http://127.0.0.1:3000
            - name: APP_URL
              value: http://localhost:3000
            - name: NEXT_PUBLIC_WS_URL
              value: ws://bot-busters.localhost
            - name: PLAYERS_PER_MATCH
              value: "2"
            - name: ALEO_NETWORK_URL # TODO: update to either minikube.internal or obscura URL
              value: http://localhost:3030
            - name: ALEO_PRIVATE_KEY
              value: APrivateKey1zkp8CZNn3yeCseEtxuVPbDCwSyhGW6yZKUYKfgXmcpoGPWH # not a real account
            - name: AWS_INFERENCE_URL
              value: https://nez5g29b86.execute-api.eu-central-1.amazonaws.com/staging/generate
# missing secrets: AWS_ACCESS_KEY, AWS_SECRET, LAMBDA_TOKEN, OBSCURA_API_KEY (not mandatory for now)
