apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-busters
spec:
  selector:
    matchLabels:
      app: bot-busters
  template:
    spec:
      containers:
        - name: bot-busters
          image: eu.gcr.io/aleo-botbusters/bot-busters/bot-busters-staging:latest
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: db_password
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: nextauth_secret
            - name: HUGGING_FACE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: hugging_face_token
            - name: DATABASE_URL
              value: postgresql://postgres:$(DB_PASSWORD)@postgres.$(POD_NAMESPACE).svc.cluster.local:5432
            - name: NEXTAUTH_URL
              value: https://bot-busters.staging.kryha.dev
            - name: NEXTAUTH_URL_INTERNAL
              value: http://127.0.0.1:3000
            - name: APP_URL
              value: http://localhost:3000
            - name: NEXT_PUBLIC_WS_URL
              value: wss://bot-busters.staging.kryha.dev
            - name: PLAYERS_PER_MATCH
              # TODO: set to correct value
              value: "3"
            - name: OBSCURA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: obscura_api_key
            - name: ALEO_NETWORK_URL
              value: https://aleo.obscura.network/v1/$(OBSCURA_API_KEY)
            - name: ALEO_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: aleo_private_key
