apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  db_password: $DB_PASSWORD
  nextauth_secret: $NEXTAUTH_SECRET
  hugging_face_token: $HUGGING_FACE_TOKEN
  aleo_private_key: $ALEO_PRIVATE_KEY
  obscura_api_key: $OBSCURA_API_KEY
  aws_access_key: $AWS_ACCESS_KEY
  aws_secret: $AWS_SECRET
