// TODO: delete

import { type LeaderboardData } from "@/types";

export const leaderboardData: LeaderboardData[] = [
  {
    rank: 1,
    score: 10000,
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    avatar: "🙂",
    username: "AliceInWonderland",
    gamesPlayed: 50,
    payout: 30,
  },
  {
    rank: 2,
    score: 9890,
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    avatar: "🙂",
    username: "BobTheBuilder",
    gamesPlayed: 50,
    payout: 29,
  },
  {
    rank: 3,
    score: 9700,
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    avatar: "🙂",
    username: "CharlieBrown",
    gamesPlayed: 50,
    payout: 28,
  },
  {
    rank: 4,
    score: 7000,
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    avatar: "🙂",
    username: "DaisyDuke",
    gamesPlayed: 50,
    payout: 27,
  },

  {
    rank: 5,
    score: 6900,
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    avatar: "🙂",
    username: "EagleEye",
    gamesPlayed: 50,
    payout: 26,
  },
  {
    rank: 6,
    score: 5688,
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    avatar: "🙂",
    username: "FancyNancy",
    gamesPlayed: 50,
    payout: 25,
  },
  {
    rank: 7,
    score: 4042,
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    avatar: "🙂",
    username: "GoldenGraham",
    gamesPlayed: 50,
    payout: 24,
  },

  {
    rank: 8,
    score: 3404,
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    avatar: "🙂",
    username: "HappyHippo",
    gamesPlayed: 50,
    payout: 23,
  },
  {
    rank: 9,
    score: 2045,
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    avatar: "🙂",
    username: "IcyIgloo",
    gamesPlayed: 50,
    payout: 22,
  },
  {
    rank: 10,
    score: 1250,
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    avatar: "🙂",
    username: "JumpingJack",
    gamesPlayed: 50,
    payout: 21,
  },
  {
    rank: 11,
    score: 870,
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    avatar: "🙂",
    username: "KangarooKid",
    gamesPlayed: 50,
    payout: 20,
  },

  {
    rank: 12,
    score: 805,
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    avatar: "🙂",
    username: "LemonLime",
    gamesPlayed: 50,
    payout: 19,
  },
  {
    rank: 13,
    score: 799,
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    avatar: "🙂",
    username: "MerryMary",
    gamesPlayed: 50,
    payout: 18,
  },
  {
    rank: 14,
    score: 706,
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    avatar: "🙂",
    username: "NiftyNancy",
    gamesPlayed: 50,
    payout: 17,
  },
  {
    rank: 15,
    score: 700,
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    avatar: "🙂",
    username: "OscarOrange",
    gamesPlayed: 50,
    payout: 16,
  },
  {
    rank: 16,
    score: 500,
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    avatar: "🙂",
    username: "PolarPenguin",
    gamesPlayed: 50,
    payout: 15,
  },
  {
    rank: 17,
    score: 377,
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    avatar: "🙂",
    username: "QuirkyQuail",
    gamesPlayed: 50,
    payout: 14,
  },

  {
    rank: 18,
    score: 340,
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    avatar: "🙂",
    username: "RacingRabbit",
    gamesPlayed: 50,
    payout: 13,
  },
  {
    rank: 19,
    score: 322,
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    avatar: "🙂",
    username: "SillySeal",
    gamesPlayed: 50,
    payout: 12,
  },
  {
    rank: 20,
    score: 312,
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    avatar: "🙂",
    username: "TumblingTiger",
    gamesPlayed: 50,
    payout: 11,
  },
  {
    rank: 21,
    score: 300,
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    avatar: "🙂",
    username: "UmbrellaUnicorn",
    gamesPlayed: 50,
    payout: 10,
  },
  {
    rank: 22,
    score: 290,
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    avatar: "🙂",
    username: "VibrantViolet",
    gamesPlayed: 50,
    payout: 9,
  },
  {
    rank: 23,
    score: 230,
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    avatar: "🙂",
    username: "WildPeter",
    gamesPlayed: 50,
    payout: 8,
  },
  {
    rank: 24,
    score: 212,
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    avatar: "🙂",
    username: "WackyWalrus",
    gamesPlayed: 50,
    payout: 7,
  },
  {
    rank: 25,
    score: 211,
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    avatar: "🙂",
    username: "XenonXylophone",
    gamesPlayed: 50,
    payout: 6,
  },
  {
    rank: 26,
    score: 150,
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    avatar: "🙂",
    username: "YellowYak",
    gamesPlayed: 50,
    payout: 5,
  },
  {
    rank: 27,
    score: 120,
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    avatar: "🙂",
    username: "ZanyZebra",
    gamesPlayed: 50,
    payout: 4,
  },
  {
    rank: 28,
    score: 100,
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    avatar: "🙂",
    username: "AppleAnna",
    gamesPlayed: 50,
    payout: 3,
  },
  {
    rank: 29,
    score: 50,
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    avatar: "🙂",
    username: "BananaBen",
    gamesPlayed: 50,
    payout: 2,
  },
  {
    rank: 30,
    score: 9,
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    avatar: "🙂",
    username: "CherryCharlie",
    gamesPlayed: 50,
    payout: 1,
  },
  {
    rank: 31,
    score: 0,
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    avatar: "🙂",
    username: "DateDiana",
    gamesPlayed: 50,
    payout: 0,
  },
];
