// TODO: delete

import { type LeaderboardData } from "~/types/index.js";

export const leaderboardData: LeaderboardData[] = [
  {
    rank: 1,
    score: 10000,
    username: "AliceInWonderland",
    matchesPlayed: 50,
    id: "a",
  },
  {
    rank: 2,
    score: 9890,
    username: "BobTheBuilder",
    matchesPlayed: 50,
    id: "b",
  },
  {
    rank: 3,
    score: 9700,
    username: "CharlieBrown",
    matchesPlayed: 50,
    id: "c",
  },
  {
    rank: 4,
    score: 7000,
    username: "DaisyDuke",
    matchesPlayed: 50,
    id: "d",
  },

  {
    rank: 5,
    score: 6900,
    username: "EagleEye",
    matchesPlayed: 50,
    id: "e",
  },
  {
    rank: 6,
    score: 5688,
    username: "FancyNancy",
    matchesPlayed: 50,
    id: "f",
  },
  {
    rank: 7,
    score: 4042,
    username: "GoldenGraham",
    matchesPlayed: 50,
    id: "g",
  },

  {
    rank: 8,
    score: 3404,
    username: "HappyHippo",
    matchesPlayed: 50,
    id: "h",
  },
  {
    rank: 9,
    score: 2045,
    username: "IcyIgloo",
    matchesPlayed: 50,
    id: "i",
  },
  {
    rank: 10,
    score: 1250,
    username: "JumpingJack",
    matchesPlayed: 50,
    id: "j",
  },
  {
    rank: 11,
    score: 870,
    username: "KangarooKid",
    matchesPlayed: 50,
    id: "k",
  },

  {
    rank: 12,
    score: 805,
    username: "LemonLime",
    matchesPlayed: 50,
    id: "l",
  },
  {
    rank: 13,
    score: 799,
    username: "MerryMary",
    matchesPlayed: 50,
    id: "m",
  },
  {
    rank: 14,
    score: 706,
    username: "NiftyNancy",
    matchesPlayed: 50,
    id: "n",
  },
  {
    rank: 15,
    score: 700,
    username: "OscarOrange",
    matchesPlayed: 50,
    id: "o",
  },
  {
    rank: 16,
    score: 500,
    username: "PolarPenguin",
    matchesPlayed: 50,
    id: "p",
  },
  {
    rank: 17,
    score: 377,
    username: "QuirkyQuail",
    matchesPlayed: 50,
    id: "q",
  },

  {
    rank: 18,
    score: 340,
    username: "RacingRabbit",
    matchesPlayed: 50,
    id: "r",
  },
  {
    rank: 19,
    score: 322,
    username: "SillySeal",
    matchesPlayed: 50,
    id: "s",
  },
  {
    rank: 20,
    score: 312,
    username: "TumblingTiger",
    matchesPlayed: 50,
    id: "t",
  },
  {
    rank: 21,
    score: 300,
    username: "UmbrellaUnicorn",
    matchesPlayed: 50,
    id: "u",
  },
  {
    rank: 22,
    score: 290,
    username: "VibrantViolet",
    matchesPlayed: 50,
    id: "v",
  },
  {
    rank: 23,
    score: 230,
    username: "WildPeter",
    matchesPlayed: 50,
    id: "w",
  },
  {
    rank: 24,
    score: 212,
    username: "WackyWalrus",
    matchesPlayed: 50,
    id: "x",
  },
  {
    rank: 25,
    score: 211,
    username: "XenonXylophone",
    matchesPlayed: 50,
    id: "y",
  },
  {
    rank: 26,
    score: 150,
    username: "YellowYak",
    matchesPlayed: 50,
    id: "z",
  },
  {
    rank: 27,
    score: 120,
    username: "ZanyZebra",
    matchesPlayed: 50,
    id: "aa",
  },
  {
    rank: 28,
    score: 100,
    username: "AppleAnna",
    matchesPlayed: 50,
    id: "ab",
  },
  {
    rank: 29,
    score: 50,
    username: "BananaBen",
    matchesPlayed: 50,
    id: "ac",
  },
  {
    rank: 30,
    score: 9,
    username: "CherryCharlie",
    matchesPlayed: 50,
    id: "ad",
  },
  {
    rank: 31,
    score: 0,
    username: "DateDiana",
    matchesPlayed: 50,
    id: "ae",
  },
];
