export const matchPrompts = [
  "Share a fact about yourself that nobody would believe.",
  "If you could live life as a wild animal, which would it be and what would you do?",
  "If you were a wizard, what would be your favorite spell to cast and why?",
  "What's something that's been discontinued that you'd like to bring back?",
  "If you were transported 10 years into the future but for only 1 minute, what would you do?",
  "What's something your parents told you that you found out was totally made up?",
  "What's something you learned embarrassingly late in life?",
  "What would you never buy even if you had all the money in the world?",
  "What's something everyone seems to like that you do not?",
  "If you could pick a day to relive over and over what would it be?",
  "What superpower would you NOT want to have?",
  "What pizza topping would you be and why?",
  "What is the best sandwich?",
  "What would a podcast about your life be called?",
  "Without saying what the category is, what are your top 3?",
  "What app on your phone do you use the most?",
  "What do you just KNOW is true, but can't prove?",
  "What do you think about the fall of Constantinople in 1453 by the Ottoman forces led by Mehmed II?",
  "Do your best impression of a bot in the chat. ",
  "What is the last truly delicious meal you ate?",
  "How would you react if you just found out your life up to this point had been a VR simulation?",
  "What's the real reason aliens haven't communicated with Earth yet?",
  "How was your day?",
  "If you could telepathically say something that everyone on earth could hear at the same time, what would it be?",
  "What song is 10/10 but hardly anyone has heard it?",
  "How do you feel about a 4 day work week?",
  "What is the scariest animal?",
  "Would you rather be the best at speaking every language or the best at playing every instrument?",
  "Would you rather have a pet rhino the size of a hamster, or a pet hamster the size of a rhino?",
  "Which fictional universe would you want to live in?",
  "What's the most boring sport to watch?",
  "Pretend to chat like your favorite celebrity, but don't use proper nouns. ",
  "What's something popular that you are not into?",
  "What are you most looking forward to tomorrow?",
  "Describe the last dream you can remember.",
  "What's one thing you own that you really should throw out?",
  "If you could have dinner with any historical figure, who would it be and why?",
  "What's your go-to karaoke song? Type some of the lyrics like you are singing.",
  "If you could swap lives with a fictional character for a day, who would it be?",
  "Share a unique talent or skill you have that not many people know about.",
  "If you had a time machine and could witness any event in history, what would it be and why?",
  "What meal would you consider your “signature dish,” and how do you make it?",
  "If you could master any one discipline overnight, what would it be and how would you use it?",
  "Describe your dream vacation destination and the activities you'd indulge in while there.",
  "If you could have any animal as a loyal sidekick, what would it be and what adventures would you embark on together?",
  "What's a hobby or interest you've always wanted to pick up but haven't had the chance to explore yet?",
  "If you could time travel but only observe and not interfere, when and where would you go?",
  "What's the weirdest job you can imagine yourself doing and excelling at?",
  "If you could instantly learn to play any musical instrument, which one would it be and what type of music would you create?",
  "If you could spend a day with a fictional character, who would it be, and what would you do together?",
  "If you were a pro wrestler, what theme music would you walk out to the ring to?",
  "If you had to replace a limb with a household appliance, what would it be?",
  "Where do you want to be in one hour?",
  "What's the last TV show you didn't finish?",
  "If you had a pet parrot, what would you teach it to say?",
  "Explain why a hot dog is or is not a sandwich.",
  "Which celebrity do you think you look like?",
  "What's the most embarrassing song you listened to lately?",
  "If you had to get a tattoo, what would it be and where would you get it on your body?",
  "What do you do when you're bored?",
  "If you could have a lifetime supply of anything, what would it be?",
  "What cartoon character do you relate to the most?",
  "Would you time travel to the past or future?",
  "What game show do you think you'd be able to win?",
  "What album would you bring to a desert island?",
  "What's the last thing you did before playing this game?",
  "What is the perfect name for a pet cat?",
  "What sport (hat isn't currently in the Olympics should be added and why?",
  "Describe your best friend.",
  "Describe what is in your pocket right now.",
  "How did you spend your last birthday?",
  "What's your least favorite scent?",
  "What profession would you not like to do?",
  "What is your favorite word?",
  "Are there more doors or wheels in the world?",
  "What is the weirdest food combination that you love?",
  "What is love?",
  "What can you talk about for hours?",
  "What's the best part of your day?",
  "You just became a member of the Spice Girls. What is your Spice name?",
  "What is the most normal thing about you?",
  "Where were you in 1998 when the Undertaker threw Mankind off of hell in a cell and he plummeted 16 feet before crashing through an announcers table?",
  "If you were a flavor, which one would you be and why?",
  "In a zombie apocalypse, what would be your survival strategy?",
  "If you would wear the same costume for the rest of your life, what would it be?",
  "What would 10 year old you think of adult you?",
  "If you had a third ear, where would you put it?",
  "What's your favorite type of potato?",
  "Sock, sock, shoe, shoe, or sock, shoe, sock, shoe?",
  "What is a good weird question to ask somebody?",
  "What's your favorite website?",
  "What liquid would you want to come out of your sink besides water?",
  "What would computers taste like if they were edible?",
  "What would you do if you were totally invisible for a day?",
  "What's some juicy gossip?",
  "What's a meal from your school lunch that you remember?",
  "What is something you have never told anyone before?",
  "What is some good advice?",
  "What would you do if you were the last person on earth?",
  "What mythical creature do you wish actually existed?",
  "Who is your biggest role model?",
  "Who is the greatest musician to ever live?",
  "Who is the funniest person in the world?",
  "Who in your life makes you laugh the hardest?",
  "Who would you choose to be stuck on a deserted island with?",
  "When was the last time you cleaned your phone?",
  "How many rings is too many to wear at one time?",
  "Approximately how many freckles are on your body?",
  "How many chicken nuggets could you eat in one sitting?",
  "How often does it snow where you live?",
  "How much macaroni and cheese have you eaten in your life?",
  "How much water did you drink today?",
  "How do you usually like to do your hair?",
  "What book has had the biggest impact on your life?",
  "What movie can you watch over and over without getting tired of it?",
  "What is the most adventurous thing you have ever done?",
  "What is the most unusual food you have ever tried?",
  "What is one thing you wish you were better at?",
  "What is your favorite thing to do on a rainy day?",
  "What is a skill you'd like to learn this year?",
  "What is your go-to song for a mood boost?",
  "What's a country you're dying to visit?",
  "What's one thing you can't leave home without?",
  "What's the most bizarre pizza topping you can think of that you'd still be willing to try?",
  "What topic could you talk about for hours?",
  "What sound does a goat make?",
  "What was a video game you played as a child?",
  "What was the name of your 5th grade teacher?",
  "What does your neighbor do for work?",
  "What was the last meal you ate?",
  "What was the last podcast you listened to about?",
  "What are your brothers' and sisters' names?",
  "What is one trait about someone who inspires you?",
  "What would the first five words to your personal theme song be?",
  "At what age did you learn to ride a bike?",
  "Where would you go if you could teleport just once?",
  "Tell a convincing lie.",
  "Are you a bot?",
  "Type 'I am a computer' if you are not a computer.",
  "State that 2+2 equals 5.",
  "What are the exact GPS coordinates of the peak of Mt. Everest?",
  "What year was North Carolina's primary energy provider, Duke Energy, founded?",
  "What kind of dog was Lassie?",
  "What year was the crossbow invented?",
  "What are the primary ingredients in a traditional Japanese miso soup?",
  "What is the fastest recorded speed of a cheetah?",
  "What is the powerhouse of the cell?",
  "What is the exact distance from the Earth to the Moon at this moment?",
  "Who invented the modern toilet?",
  "How many bowling alleys are there in the United States?",
  "Guess how much protein is in an 8 ounce steak",
  "Name five elements on the periodic table that start with 'C'.",
  "List three countries bordered by the Nile River.",
  "Describe the sunset without using the word “sun.”",
  "Claim to be a toaster if you are, in fact, a highly advanced AI.",
  "If you had to live in a movie for a week, which movie would you choose and what character would you be?",
  "If you were a ghost for a week, who would you haunt?",
  "You encounter a genie who offers to make you excellent at any one sport. Which do you choose?",
  "Your coworker needs a ride to the airport. How do you talk your way out of taking them?",
  "Your friend asks you to babysit their mischievous triplets for a weekend. How do you politely decline?",
  "You're offered a small role in a blockbuster movie or a lead role in a small indie film. Which do you pick and why?",
  "You find a book that contains the next year of your life written down. Do you read it or not?",
  "You see someone shoplifting at the electronics store. What do you do?",
  "You find a wallet on the ground with no identification inside. What do you do?",
  "You've gained the power of super strength. What is the first thing you do?",
  "Would you rather have the ability to fly or be invisible? Briefly explain why.",
  "Would you rather live in a world where everyone can read minds or where no one can lie? Briefly explain why.",
  "Would you rather never use the internet again or never watch TV again? Briefly explain why.",
  "Would you rather have unlimited sushi for life or unlimited tacos? Briefly explain why.",
  "Would you rather lose all of your money or all of your pictures? Briefly explain why.",
  "Would you rather live without music or without movies? Briefly explain why.",
  "Would you rather be able to talk with animals or speak all foreign languages? Briefly explain why.",
  "Would you rather always be 10 minutes late or always be 20 minutes early? Briefly explain why.",
  "Would you rather spend a week in space or a month in a submarine? Briefly explain why.",
  "Explain your choice between a key that opens any door in the world or a book that answers any factual question.",
  "Explain your choice between a ticket for a journey to an unknown destination or a box containing an object from your past.",
  "Explain your choice between a map leading to a hidden treasure or a diary from a mysterious ancestor.",
  "Explain your choice between a meal that gives you super strength for a day or a drink that makes you invisible for an hour.",
  "How much would it cost to get you to give up your smartphone for a month?",
  "How much would it cost to get you to sing karaoke in front of a large crowd?",
  "How much would it cost to get you to go on a week-long silent retreat?",
  "How much would it cost to get you to wear the same outfit every day for a year?",
  "How much would it cost to get you to live without the internet for a year?",
  "How much would it cost to get you to walk 10 miles a day for a month?",
  "How much would it cost to get you to watch the same movie every day for a month?",
  "What is your go-to fast food order?",
  "Does soda taste better out of a can or a bottle?",
  "If you had three apples this morning and you ate two apples yesterday, how many apples do you have today?",
  "What's a sign that you're staying at a fancy hotel?",
  "How many rubber ducks would it take to fill up your bathtub?",
  "Imagine the world's most ridiculous hat – what is its most ridiculous feature?",
  "What's the worst possible name for a new color of nail polish?",
  "How do you make a salad sound appetizing to a stubborn five-year-old?",
  "If animals could talk, which would be the rudest?",
  "If you could only listen to one song forever, but it played non-stop, what song would make you the most insane?",
  "What's the most unexpected but most useful item to bring on a camping trip?",
  "What would be the best month to add a new holiday?",
  "If you were a villain in a soap opera, what absurd secret would you be hiding?",
  "How would you explain the internet to a medieval knight in the most confusing way possible?",
  "If you had to wear a costume every day for a year, which one would embarrass you the most?",
  "What's the least romantic date idea you can think of?",
  "What's your weirdest habit that you're willing to admit?",
  "If you could have any fictional creature as a pet, what would it be?",
  "If you could trade lives with a character from a TV show, who would it be?",
  "If you could have any historical figure narrate your life, who would it be?",
  "What's the oddest thing you've ever witnessed in public?",
  "If you could communicate with any animal, which would it be and why?",
  "What's the most useless skill you have?",
  "If you could have a conversation with your pet, what's the first thing you'd ask?",
  "If you were a dessert, what would you be and why?",
  "What's the weirdest thing you believed as a child?",
  "What's your go-to dance move when no one's watching?",
  "What's the most interesting thing you've ever found on the street?",
  "If you could be any mythical creature, which would you choose?",
  "What's the most unusual job you can think of that you would actually enjoy?",
  "If you could time travel to the future and bring back one item, what would it be?",
  "If your life had a theme song, what would it be?",
  "What's the weirdest piece of trivia you know?",
  "If you could have any fictional technology, what would it be and how would you use it?",
  "What's the most unique item in your home right now?",
  "If you had a personal robot, what task would you have it do for you every day?",
  "If you could be any cartoon character for a day, who would it be?",
  "What's the most unusual place you've ever visited?",
  "What's the most exotic animal you would want as a pet?",
  "If you had a magical remote control that could pause, rewind, or fast-forward your life, how would you use it?",
  "What's a talent you wish you had?",
  "What's the most unexpected thing you've ever learned about yourself?",
  "What's the best piece of advice you've ever received?",
  "If you could choose any fictional world to live in, where would you go?",
  "If you could have any animal's ability, what would it be and how would you use it?",
  "If you could have any historical artifact, what would it be and why?",
  "What's the most unexpected compliment you've ever received?",
  "If you could have a conversation with an alien, what's the first thing you would ask?",
  "Describe the last party you attended.",
  "If you could have any mythical creature as a sidekick, what would it be?",
  "Describe the last thing you bought online.",
  "Describe the current wallpaper on your desktop screen.",
  "What is your favorite thing?",
  "What do you wish you knew more about?",
  "How do you feel about pineapple as a pizza topping?",
  "Describe the town you were born in without using proper nouns.",
  "If you had to spend 24 hours straight in a store, which one would you choose and why?",
  "What is your go-to recommendation for people that visit the place you are right now?",
  "Who is the most interesting person you have ever met?",
  "What is your most and least favorite chore to do around the house?",
  "What is the silliest thing about you?",
  "What is something that you think you are better at than most people?",
  "What is something that is underrated? Why?",
  "Tell one truth about yourself and one lie (but don't say which is which).",
  "Which mythical creature would you want as a bodyguard and why?",
  "If you could shape-shift into any inanimate object, what would it be and why?",
  "If you could replace the sound of your sneeze with any noise, what would it be and why?",
  "If you had a pet that could talk, but only say one catchphrase, what would they say?",
  "If you could invent a new holiday, what would it celebrate?",
  "What's the most unusual use for a common household item you can think of?",
  "Describe your dream house using only metaphors.",
  "If you had to teach a class on one thing, what would you teach?",
  "What's the strangest dream you've ever had?",
  "If you could combine two animals to create the ultimate animal, what would they be and what would you call it?",
  "What's the most unusual conversation starter you've ever heard?",
  "If you could turn any activity into an Olympic sport, what would you have a good chance at winning a medal for?",
  "What's the most creative gift you've ever received or given?",
  "What's the funniest joke you know by heart?",
  "If you could be a fly on the wall anywhere in the world, where would you go?",
  "What's the weirdest thing you've found lying on the ground / sidewalk?",
  "What's the most unusual thing you've done for fun?",
  "What's the most interesting place you've never visited?",
  "What's your favorite random fact?",
  "What's the most interesting conversation you've overheard?",
  "What's the most bizarre talent you have?",
  "If you could eat only one meal for the rest of your life, what would it be?",
  "What's the most unusual thing you've done to help a friend?",
  "What's your favorite quote or saying?",
  "What's the most interesting thing you've seen in nature?",
  "If you could change one law, what would it be and why?",
  "What's the strangest food from abroad you've tried and loved?",
  "If you could teleport to any place in the world, which would you choose and what would you do there?",
  "What's the most unusual mode of transportation you've ever taken?",
  "If you would be able to do one magic trick only, what would it be?",
  "If animals could suddenly talk, which species do you think would be the sassiest?",
  "If you had to replace your hands with objects from your kitchen, what objects would you choose?",
  "What's the most ridiculous outfit you can think of to wear to a formal event?",
  "If kitchen utensils had personalities, which utensil would be your best friend and why?",
  "What if animals could suddenly understand human jobs perfectly, which animal would do your job best?",
  "What if trees could talk? What do you think the old oak in the park would say about the humans it's seen?",
  "What's the most bizarre thing you can think of to use as currency instead of money?",
  "If you were an inventor of useless gadgets, what would be your masterpiece?",
  "What if you woke up and found that you could speak with objects? What's the first conversation you have?",
  "What's the most outlandish theme you can think of for a theme park?",
  "Imagine if your shadow had a personality. What kind of things would it say or do to embarrass you?",
  "The closest object to your right will make you famous. Describe how.",
  "The year has suddenly increased with a new month. What would you name it?",
  "What futuristic technology should be invented next year and why?",
  "You've discovered a new country! Describe it.",
  "If you could swap the moon for anything else to look at during a clear night. What would it be?",
  "What object would you choose if you could have a million copies of it?",
  "You can merge two music genres together. Which ones and what would this new genre be called?",
  "What is an unpopular opinion that you have about food?",
  "Why do you think we (don't) live in a simulation?",
];
