export const match = {
  chat: "Start chatting",
  voting: "Let’s bust some bots",
  inThisChat: "In this chat room you appear as",
  otherParticipants: "Other participants in this room",
  whosBot: "Who's bot and who's not?",
  isBot: "Bot",
  isHuman: "Human",
  localPlayer: "(YOU)",
  bustTheBots: "Bust the bots",
  bustTheBotsDescription: "Click to vote for one or multiple suspected BOTS.",
  bustTheBotsDisabled: "Bust the bots",
  bustTheBotsDisabledDescription:
    "Voting is only available for players participating in the chat.",
  botBusted: "Bot busted!",
  wrongBust: "Wrong Bust",
  missedBot: "Missed Bot",
  isBotSelect: "Bot?",
  busted: "Busted!",
  bummer: "Bummer!",
  goodJobKinda: "Good job, kinda...",
  bustedResultPass: "You did your busting duty but also chose incorrectly",
  bustedResultFail: "You failed. Try again.",
  resultHumanTitle: "was played by a human!",
  resultBotTitle: "was played by a bot!",
  resultBotHuman: "was played by an unverified human!",
  resultBot: "A Proof of AI was generated upon selecting this bot using Aleo.",
  resultHuman: "A Proof of Humanity was generated using zPass and Aleo.",
  verifyProof: "Check and verify the proof",
};
