export const match = {
  chat: "Start chatting",
  voting: "Let’s bust some bots",
  inThisChat: "In this chat room you appear as",
  otherParticipants: "Other participants in this room",
  whosBot: "Who's bot and who's not?",
  isBot: "Bot",
  isHuman: "Human",
  localPlayer: "(YOU)",
  bustTheBots: "Bust the bots",
  bustTheBotsDescription: "Click to vote for one or multiple suspected BOTS.",
  botBusted: "Bot busted!",
  isNotBot: "is not a bot",
  isBotSelect: "Bot?",
  busted: "Busted!",
  bustedResultPass: "A Winner is You!",
  bustedResultFail: "You lost. Try again.",
};
