name: Build and Deploy staging to GKE

on:
  push:
    branches:
      # - "main"
      - "fix/skaffold-cache"

env:
  PROJECT_ID: aleo-botbusters
  GKE_CLUSTER: bot-busters
  GKE_ZONE: europe-west1-b

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy staging
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: auth
        name: Authenticate with GCloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - id: get-credentials
        name: Retrieve GCloud credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - id: skaffold-install
        name: Download and install Skaffold
        run: |-
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && sudo install skaffold /usr/local/bin/

      - id: build-and-push
        name: Build and push Docker images
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          HUGGING_FACE_TOKEN: ${{ secrets.HUGGING_FACE_TOKEN }}
          ALEO_PRIVATE_KEY: ${{ secrets.ALEO_PRIVATE_KEY }}
          OBSCURA_API_KEY: ${{ secrets.OBSCURA_API_KEY }}
        run: |-
          envsubst < deployment/staging/secrets.template.yaml > deployment/staging/secrets.yaml
          skaffold run --filename skaffold.staging.yml --cache-artifacts=false
